#!/usr/bin/env bash
# scripts/export-abis.sh
# Run from repo root: bash scripts/export-abis.sh
# Copies compiled contract ABIs from forge out/ to frontend/src/abis/
# Requires: forge build to have run first

set -euo pipefail

CONTRACTS_DIR="chainx/contracts"
OUT_DIR="$CONTRACTS_DIR/out"
ABIS_DIR="chainx/frontend/src/abis"

echo "▶ Building contracts..."
(cd "$CONTRACTS_DIR" && forge build --silent)

echo "▶ Exporting ABIs to $ABIS_DIR ..."
mkdir -p "$ABIS_DIR"

contracts=(
  "StakeholderRegistry"
  "ProductRegistry"
  "ZKVerifier"
  "Escrow"
)

for contract in "${contracts[@]}"; do
  src="$OUT_DIR/${contract}.sol/${contract}.json"
  if [[ -f "$src" ]]; then
    # Extract only the abi array (not full artifact) using jq
    jq '.abi' "$src" > "$ABIS_DIR/${contract}.abi.json"
    echo "  ✓ $contract"
  else
    echo "  ✗ $contract — not found at $src"
    exit 1
  fi
done

echo "▶ Generating TypeScript barrel..."
cat > "$ABIS_DIR/index.ts" << 'EOF'
// Auto-generated by scripts/export-abis.sh — do not edit manually

export { default as stakeholderRegistryAbi } from './StakeholderRegistry.abi.json'
export { default as productRegistryAbi }     from './ProductRegistry.abi.json'
export { default as zkVerifierAbi }          from './ZKVerifier.abi.json'
export { default as escrowAbi }              from './Escrow.abi.json'
EOF

echo "▶ ABI export complete."
