// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title  ZKVerifier
 * @notice Groth16 verifier for the DeliveryProof circuit.
 *
 *         ⚠️  This file is a STUB.
 *         The real verifier is generated by:
 *           snarkjs zkey export solidityverifier \
 *             circuits/keys/delivery_final.zkey \
 *             contracts/src/ZKVerifier.sol
 *
 *         Replace the body of verifyProof() with the snarkjs-generated
 *         assembly once you have run the trusted setup.
 *
 *         Public signals layout (matches circuit public inputs):
 *           pubSignals[0] = productId
 *           pubSignals[1] = windowStart
 *           pubSignals[2] = windowEnd
 *           pubSignals[3] = committedHash
 */
contract ZKVerifier {
    /**
     * @notice Verify a Groth16 proof.
     * @param  pA         G1 proof element A.
     * @param  pB         G2 proof element B.
     * @param  pC         G1 proof element C.
     * @param  pubSignals Public circuit outputs (4 values).
     * @return bool       True iff the proof is valid.
     */
    function verifyProof(
        uint256[2]    calldata pA,
        uint256[2][2] calldata pB,
        uint256[2]    calldata pC,
        uint256[4]    calldata pubSignals
    ) public view returns (bool) {
        // ── Pairing check (generated by snarkjs) ──────────────────────────────
        // TODO: replace with generated pairing library + IC/vk constants.
        //
        // For local testing this stub returns true so Escrow tests can run
        // without a real trusted setup. Replace before production deployment.
        //
        // Suppress unused-variable warnings
        pA;
        pB;
        pC;
        pubSignals;

        return true; // STUB — replace with real verifier
    }
}